table_name: 10111
policies:
  - type: uid
    uid_range: 963:963
    killswitch: true
  - type: uid
    uid_range: 972:972
    killswitch: false
interface: wg0
ipv6: false
nets:
  - 192.168.0.0/24
vpn:
  type: wireguard
  interface:
    address:
      - fd9f:1234::4/128
      - 10.6.6.45/32
    private_key: abc
  peer:
    public_key: def
    # omit preshared_key if you don't have one
    preshared_key: xyz
    allowed_ips:
      - 0.0.0.0/0
      - ::0/0
    endpoint: example.com:51820
    keepalive: 16
